packages:
  - "apps/*"
  - "packages/*"
  - "packages/ashby-jobs/actor"
  - "packages/breezyhr-jobs/actor"
  - "packages/greenhouse-jobs/actor"
  - "packages/hn-jobs/actor"
  - "packages/lever-jobs/actor"
  - "packages/personio-jobs/actor"
  - "packages/recruitee-jobs/actor"
  - "packages/smartrecruiters-jobs/actor"
  - "packages/workable-jobs/actor"
  - "packages/bamboohr-jobs/actor"
  - "packages/teamtailor-jobs/actor"
  - "packages/pinpoint-jobs/actor"
  - "packages/dover-jobs/actor"
  - "packages/jazzhr-jobs/actor"
  - "packages/jobvite-jobs/actor"
  - "packages/deadlyaccuratejobs/actor"
