import { sqliteTable, text, integer, uniqueIndex, index } from "drizzle-orm/sqlite-core";

export const jobs = sqliteTable("jobs", {
  id: text("id").primaryKey(),
  source: text("source").notNull(),
  sourceId: text("source_id").notNull(),
  company: text("company").notNull(),
  companySlug: text("company_slug").notNull(),
  title: text("title").notNull(),
  department: text("department").default(""),
  location: text("location").default(""),
  country: text("country").default(""),
  region: text("region").default("other"),
  isRemote: integer("is_remote", { mode: "boolean" }).notNull().default(false),
  employmentType: text("employment_type").default(""),
  salary: text("salary").default(""),
  applyUrl: text("apply_url").notNull(),
  jobUrl: text("job_url").default(""),
  publishedAt: text("published_at").default(""),
  scrapedAt: text("scraped_at").notNull(),
  tags: text("tags").default(""),
  descriptionSnippet: text("description_snippet").default(""),
  lastSeenAt: text("last_seen_at").default(""),
  isStale: integer("is_stale", { mode: "boolean" }).notNull().default(false),
  isDuplicateOf: text("is_duplicate_of").default(""),
}, (table) => [
  uniqueIndex("idx_source_sourceId").on(table.source, table.sourceId),
  index("idx_region").on(table.region),
  index("idx_is_remote").on(table.isRemote),
  index("idx_published_at").on(table.publishedAt),
  index("idx_company_slug").on(table.companySlug),
  index("idx_source").on(table.source),
  index("idx_published_id").on(table.publishedAt, table.id),
]);
